from random import randrange

#Prénom Féminin
prenom_f_elf = [
"Aerin",
"Aredhel (noble elfe)",
"Arien",
"Arwen (demoiselle royale)",
"Celebrían (reine d'argent)",
"Earwen (jeune fille de la mer)",
"Elbereth (étoile-reine),",
"Eledhwen (au teint d'elfe),",
"Elenna (vers les étoiles),",
"Enetari (étoile-reine),",
"Elenwë (l'étoilée),",
"Elerinna (couronnée d'étoiles),",
"Elwing (pluie d'étoiles),",
"Estë (repos),",
"Galadriel (Jeune Fille Couronnée, d'une Guirlande Radieuse)",
"Glingal (la flamme suspendue)",
"Glóredhel,",
" Idril,",
"Ilmarë,",
"Indis,",
"Isil (la lune),",
"Kementari (reine de la terre),",
"Lalwendë (jeune fille rieuse),",
"Laurelin (le chant d'or),",
"Linaewen (lac des oiseaux),",
" Lindorië,",
" Luinil (étoile à la lumière bleue)",
"Lúthien,",
"Manîthil (esprit de lune)",
"Melian (Cadeau Chéri ),",
"Míriel (Dame Joyau) ,",
"Mormegil (l'épée noire),",
" Morwën (Dame noire,sombre),",
"Nennvial (lac du crépuscule),",
"Nerdanel,",
"Nerwen (fille masculine)",
"Nienor (deuil),",
" Níniel (fille aux larmes)",
"Ninquelotë (fleur blanche)",
"Oilossë (neige toujours blanche)",
"Rathlóriel (lit d'or)",
"Serindë (la brodeuse)",
"Silmarien (amoureuse des silmarils)",
"Thuringwethil (femme de l'ombre secrète)",
"Tintallë (l'allumeuse)",
"Tinúviel (fille du Crépuscule)",
"Vairë (la tisseuse)",
"Varda (la très haute)",
"Yavana (dispensatrice des fruits)"
]

#Prénom Masculin
prenom_m_elf = [
"Adanedhel : homme-elfe",
"Adûnakhôr : seigneur de l’Ouest",
"Aeglos : pointe de Neige",
"Aegnor : feu cruel",
"Aerandir vagabond des mers",
"Argawaen taché de sang",
"Aldaron seigneur des arbres",
"Anario : soleil",
"Arcadio",
"Aranrùth : la colère du roi",
"Ancalagon",
"Anfauglith : poussière d’agonie",
"Atanatar : pére des hommes",
"Astaldo : le vaillant",
"Aulendil : ami d’aulë",
"Aulendur : serviteur",
"Balan",
"Baragund",
"Belegund",
"Bëor",
"Boromir : Joyau Loyal",
"Bregolas",
"Bronweg",
"Bruithwir",
"Calimehtar : guérrier de lumière",
"Calimmacil : épée de lumière",
"Calion : le lumineux",
"Calywen",
"Carcharoth : les mâchoires sanglantes",
"Castamir : joyaux",
"Celeborn : arbre d’argent",
"Ciryaher : seigneur des navires",
"Ciryandil : ami des naviresé",
"Ciryatan : constructeur de navire",
"Círyon",
"Círdan : le bâtisseur",
"Cirth : les runes",
"Cuthalion : arc de fer",
"Daeron",
"Dagnir : le tourmenteur",
"Deldúwath : horreur des Ombres de la Nuit",
"Denethor",
"Dimrost : les marches de la pluie",
"Dovahkiin : enfant des dragons",
"Duinhir : Seigneur de la rivière",
"Eärendur : serviteur de la mer",
"Eldacar : heaume",
"Eldarion",
"Elendur : serviteur des étoiles",
"Elendil : ami des elfes/ étoiles",
"Elrond : voûte étoilée",
"Elros (écume d’étoile)",
"Eöl",
"Erchamion : le manchot",
"Falastur : seigneur des côtes",
"Fantur : maitre",
"Faramir : Joyau Suffisant",
"Fëanor[o] : l’esprit du feu",
"Felagund : seigneur des cavernes",
"Finwë",
"Fírimar : mortels",
"Gondolin : le roc caché",
"Gorthol : heaume de terreur",
"Gundor",
"Gurthang : le fer de la mort",
"Gwindor",
"Helevorn : verre noir",
"Herendil : ami de la fortune",
"Herumor : seigneur noir",
"Herunúmes : seigneur de l’ouest",
"Hyamendacil : vainqueur du sud",
"Imlach",
"Ingwë",
"Irmo",
"Isil : éclat argenté",
"Isildur",
"Lastalaica : celui qui écoute",
"Legolas : vertes feuilles",
"Lenwë",
"Lómelindi : chanteur de crépuscule",
"Lómion : fils du crépuscule",
"Lorgan",
"Lórindol : tête d’or",
"Maedhros",
"Mahtan",
"Mardil : ami du roi",
"Maglor",
"Magor",
"Meneldil",
"Narmacil : épée de feu",
"Nandor : ceux qui font demi-tour",
"Nómin : le sage",
"Ohtar : guerrier",
"Ostoher : seigneur de la citadelle",
"Radagast",
"Radhruin",
"Ragnor",
"Rána : le voyageur",
"Palantir : qui regarde au loin et partout",
"Pelendul : serviteur de la cité",
"Rauros : grondement d’écume",
"Rorhirrim : prince à cheval",
"Rómendacil : vainqueur de l’est",
"Russandol : tête de cuivre",
"Saeros",
"Salmar",
"Saruman : homme habile",
"Sauron : le détesté",
"Seregon : sang de pierre",
"Silmarien",
"Siriondil : ami de Sirion",
"Sindar : manteau gris",
"Súlimo : celui qui respire",
"Tarannon : don royal",
"Targen",
"Terendul : grand ténébreux",
"Turindo : maitre de son coeur",
"Tauron : seigneur des forêts",
"Turucàno : seigneur et maitre",
"Tyeplerinquar : poigne d’argent",
"Telchar",
"Telemnar",
"Teleri : les derniers",
"Thalion : inébranlable, fort",
"Thalos",
"Thorondor : Roi des aigles",
"Tilion",
"Tulkas : le plus grand pour la force et la vaillance",
"Turambar : maître du destin",
"Uldor",
"Ulmo : celui qui aime la pluie",
"Ulwarth",
"Umarth : mauvais sort",
"Urthel",
"Urulóki : serpent de feu",
"Valar : les puissants",
"Valacar : Heaume de puissance",
"Valaraukar : démons de la terreur",
"Vanyar : blond",
"Vása : le dévoreur",
"Vorondil : ami véritable",
]

rep = str()

print("Voici le générateur de prénom elfique") 
print("Appuyez sur 'q' à tout moment pour quitter")
while rep != "q": 
    rep = input("Etes-vous un Homme ou une Femme? (H/F):  ")   
    if rep == "H" or rep == "h" or rep == "Homme" or rep == "homme": #Prénom masculin
        print("\nVous avez dit que vous etes un Homme, voici un prénom qui peut vous convenir\n")
        max_m = len(prenom_m_elf) - 1
        prenom_m_elfR = randrange(max_m)
        prenom_m_ = prenom_m_elf[prenom_m_elfR]
        print("\n Votre Prenom est:")
        print(str("\n" + prenom_m_.title().center(50) + "\n"))
        continue
    elif rep == "F" or rep == "f" or rep == "Femme" or rep == "femme": #Prénom féminin
        print("\nVous avez dit que vous êtes une Femme, voici un prénom qui peut vous convenir\n")
        max_f = len(prenom_f_elf) - 1
        prenom_f_elfR = randrange(max_f)
        prenom_f_ = prenom_f_elf[prenom_f_elfR]
        print("\n Votre Prenom est: ")
        print(str( "\n" + prenom_f_.title().center(50) + "\n"))
        continue
    elif rep == "q" or rep == "Q" or rep == "Quitter" or rep == "Fin":
        print("Merci d'avoir utilisez ce Générateur de Prénom elfique, au plaisir de vous revoir")        
    else:
        print("Je n'ai pas compris, veuillez entrez un genre svp")   
        continue    
        
    input("Entrez pour sortir du programme")